// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vehicle_Config_DotNet_.Repositories;

#nullable disable

namespace Vehicle_Config_DotNet_.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.AltComponent", b =>
                {
                    b.Property<long>("AltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("alt_id");

                    b.Property<long>("AltCompId")
                        .HasColumnType("bigint")
                        .HasColumnName("alt_comp_id");

                    b.Property<long>("CompId")
                        .HasColumnType("bigint")
                        .HasColumnName("comp_id");

                    b.Property<long>("ModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_id");

                    b.Property<double>("PriceVariation")
                        .HasColumnType("double")
                        .HasColumnName("price_variation");

                    b.HasKey("AltId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AltCompId" }, "FKgvcwehmbldv5wtks58m5pxipg");

                    b.HasIndex(new[] { "CompId" }, "FKh6wwkiru12oixcdy55to8y3xp");

                    b.HasIndex(new[] { "ModelId" }, "FKiaxybepfrjxkrov9xnwl6fbtv");

                    b.ToTable("alt_components");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.CompanyInfo", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("AreaCity")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("area_city");

                    b.Property<string>("AuthorizedCell")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("authorized_cell");

                    b.Property<string>("AuthorizedPersonName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("authorized_person_name");

                    b.Property<string>("AuthorizedTel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("authorized_tel");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("Designation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fax");

                    b.Property<string>("HoldingType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("holding_type");

                    b.Property<string>("PanNo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pan_no");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PinCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pin_code");

                    b.Property<string>("StNo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("st_no");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("state");

                    b.Property<string>("Tel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tel");

                    b.Property<string>("VatRegNo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vat_reg_no");

                    b.HasKey("CompanyId")
                        .HasName("PRIMARY");

                    b.ToTable("company_info");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Component", b =>
                {
                    b.Property<long>("CompId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("comp_id");

                    b.Property<string>("CompName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comp_name");

                    b.HasKey("CompId")
                        .HasName("PRIMARY");

                    b.ToTable("components");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Invoice", b =>
                {
                    b.Property<int>("InvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inv_id");

                    b.Property<string>("Components")
                        .HasColumnType("longtext")
                        .HasColumnName("components");

                    b.Property<string>("Date")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<double?>("GstAmount")
                        .HasColumnType("double")
                        .HasColumnName("gst_amount");

                    b.Property<string>("InvoiceId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("invoice_id");

                    b.Property<string>("ModelName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model_name");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("double")
                        .HasColumnName("total_price");

                    b.Property<double?>("TotalWithgst")
                        .HasColumnType("double")
                        .HasColumnName("total_withgst");

                    b.HasKey("InvId")
                        .HasName("PRIMARY");

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Manufacturer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ManuName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("manu_name");

                    b.Property<int>("SegId")
                        .HasColumnType("int")
                        .HasColumnName("seg_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SegId" }, "FKvt86n4h6jurg9ofnq26txaw7");

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Model", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_path");

                    b.Property<long?>("ManuId")
                        .HasColumnType("bigint")
                        .HasColumnName("manu_id");

                    b.Property<int>("MinQty")
                        .HasColumnType("int")
                        .HasColumnName("min_qty");

                    b.Property<string>("ModName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mod_name");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int?>("SafetyRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("safety_rating")
                        .HasDefaultValueSql("'5'");

                    b.Property<int?>("SegId")
                        .HasColumnType("int")
                        .HasColumnName("seg_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SegId" }, "FKeoehxbf066gnexos8p4o9fn5e");

                    b.HasIndex(new[] { "ManuId" }, "FKr7t3perk8n5abjcuk8j3kn9ko");

                    b.ToTable("models");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("SegName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("seg_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("segments");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.VehicleDetail", b =>
                {
                    b.Property<long>("ConfiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("confi_id");

                    b.Property<long>("CompId")
                        .HasColumnType("bigint")
                        .HasColumnName("comp_id");

                    b.Property<string>("CompType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("comp_type")
                        .IsFixedLength();

                    b.Property<string>("IsConfigurable")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("is_configurable")
                        .IsFixedLength();

                    b.Property<long>("ModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_id");

                    b.HasKey("ConfiId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelId" }, "FK4xnsh93sp191ava4jva94peds");

                    b.HasIndex(new[] { "CompId" }, "FKq35ocm7yckn0ak8jrsk06l0c3");

                    b.ToTable("vehicle_details");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.AltComponent", b =>
                {
                    b.HasOne("Vehicle_Config_DotNet_.Models.Component", "AltComp")
                        .WithMany("AltComponentAltComps")
                        .HasForeignKey("AltCompId")
                        .IsRequired()
                        .HasConstraintName("FKgvcwehmbldv5wtks58m5pxipg");

                    b.HasOne("Vehicle_Config_DotNet_.Models.Component", "Comp")
                        .WithMany("AltComponentComps")
                        .HasForeignKey("CompId")
                        .IsRequired()
                        .HasConstraintName("FKh6wwkiru12oixcdy55to8y3xp");

                    b.HasOne("Vehicle_Config_DotNet_.Models.Model", "Model")
                        .WithMany("AltComponents")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FKiaxybepfrjxkrov9xnwl6fbtv");

                    b.Navigation("AltComp");

                    b.Navigation("Comp");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Manufacturer", b =>
                {
                    b.HasOne("Vehicle_Config_DotNet_.Models.Segment", "Seg")
                        .WithMany("Manufacturers")
                        .HasForeignKey("SegId")
                        .IsRequired()
                        .HasConstraintName("FKvt86n4h6jurg9ofnq26txaw7");

                    b.Navigation("Seg");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Model", b =>
                {
                    b.HasOne("Vehicle_Config_DotNet_.Models.Manufacturer", "Manu")
                        .WithMany("Models")
                        .HasForeignKey("ManuId")
                        .HasConstraintName("FKr7t3perk8n5abjcuk8j3kn9ko");

                    b.HasOne("Vehicle_Config_DotNet_.Models.Segment", "Seg")
                        .WithMany("Models")
                        .HasForeignKey("SegId")
                        .HasConstraintName("FKeoehxbf066gnexos8p4o9fn5e");

                    b.Navigation("Manu");

                    b.Navigation("Seg");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.VehicleDetail", b =>
                {
                    b.HasOne("Vehicle_Config_DotNet_.Models.Component", "Comp")
                        .WithMany("VehicleDetails")
                        .HasForeignKey("CompId")
                        .IsRequired()
                        .HasConstraintName("FKq35ocm7yckn0ak8jrsk06l0c3");

                    b.HasOne("Vehicle_Config_DotNet_.Models.Model", "Model")
                        .WithMany("VehicleDetails")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FK4xnsh93sp191ava4jva94peds");

                    b.Navigation("Comp");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Component", b =>
                {
                    b.Navigation("AltComponentAltComps");

                    b.Navigation("AltComponentComps");

                    b.Navigation("VehicleDetails");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Model", b =>
                {
                    b.Navigation("AltComponents");

                    b.Navigation("VehicleDetails");
                });

            modelBuilder.Entity("Vehicle_Config_DotNet_.Models.Segment", b =>
                {
                    b.Navigation("Manufacturers");

                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
